"""empty message

Revision ID: 67b59caf77f0
Revises: e05aede23ea8
Create Date: 2021-12-08 16:25:00.887132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b59caf77f0'
down_revision = 'e05aede23ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address_id', sa.Integer(), nullable=True))
    op.drop_constraint('users_adress_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'addresses', ['address_id'], ['id'])
    op.drop_column('users', 'adress_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('adress_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_adress_id_fkey', 'users', 'addresses', ['adress_id'], ['id'])
    op.drop_column('users', 'address_id')
    # ### end Alembic commands ###
