"""user_cpf -> user_email

Revision ID: 9a57d7b5e008
Revises: 6fa28c6227e4
Create Date: 2021-12-13 11:30:48.455574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a57d7b5e008'
down_revision = '6fa28c6227e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('republics', sa.Column('user_email', sa.String(), nullable=True))
    op.drop_constraint('republics_user_cpf_fkey', 'republics', type_='foreignkey')
    op.create_foreign_key(None, 'republics', 'users', ['user_email'], ['email'])
    op.drop_column('republics', 'user_cpf')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('republics', sa.Column('user_cpf', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'republics', type_='foreignkey')
    op.create_foreign_key('republics_user_cpf_fkey', 'republics', 'users', ['user_cpf'], ['cpf'])
    op.drop_column('republics', 'user_email')
    # ### end Alembic commands ###
