"""Assuring 1:1 relation between republic and address

Revision ID: b6a871638396
Revises: d32688e6e055
Create Date: 2021-12-09 23:28:36.587880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6a871638396'
down_revision = 'd32688e6e055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'republics', ['address_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'republics', type_='unique')
    # ### end Alembic commands ###
