"""empty message

Revision ID: 8e916c72d5b8
Revises: e168aa0b9d01
Create Date: 2021-12-09 11:55:03.275941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e916c72d5b8'
down_revision = 'e168aa0b9d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pictures_picture_url_key', 'pictures', type_='unique')
    op.add_column('republics', sa.Column('user_cpf', sa.String(), nullable=True))
    op.drop_constraint('republics_student_cpf_fkey', 'republics', type_='foreignkey')
    op.create_foreign_key(None, 'republics', 'users', ['user_cpf'], ['cpf'])
    op.drop_column('republics', 'student_cpf')
    op.alter_column('users', 'password',new_column_name='password_hash')    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',new_column_name='password')
    op.add_column('republics', sa.Column('student_cpf', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'republics', type_='foreignkey')
    op.create_foreign_key('republics_student_cpf_fkey', 'republics', 'users', ['student_cpf'], ['cpf'])
    op.drop_column('republics', 'user_cpf')
    op.create_unique_constraint('pictures_picture_url_key', 'pictures', ['picture_url'])
    # ### end Alembic commands ###
